### ISSUE TITLE
ImageSharp issue when using ?width parameter

### ISSUE THREAD

**Issue by binraider** [adam-werner/Umbraco.StorageProviders.AWSS3#11]
Hi There. 

We have 5 production setups and on one of them there is a strange issue. We use docker/fargate Umbraco 10.5.1. version 1.1.1 of the storage provider. We recently upgrade from U8 to U10. On one setup the Umbraco thumbnails all cause a 500 error. Basically as soon as we add the ?width we get a 500.

![image](https://github.com/adam-werner/Our.Umbraco.StorageProviders.AWSS3/assets/38069359/afc597b1-74ea-45f0-a324-b475352d83b0)

Here are the logs from Umbraco:

Amazon.S3.AmazonS3Exception: The specified key does not exist.
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Util.AmazonS3Util.DoesS3BucketExistV2Async(IAmazonS3 s3Client, String bucketName)
   at Our.Umbraco.StorageProviders.AWSS3.Imaging.AWSS3FileSystemImageProvider.GetResolverAsync(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

Could it be related to permissions on the cache folder in the s3 bucket? Although that side of things has not changed during the upgrade to Umbraco 10.

**Comment by adam-werner** [comment]
Hello @binraider!  Interesting issue and I'd be curious to understand it a bit more.  

It could be possible that its a permissions issue on the cache folder, but if other media without querystring parameters are being returned, I think we might be able to rule that out.

You've indicated that you have 5 production setups.  Is this issue with the addition of the "?width" to an image being experienced in each of the 5 or just in the 1 instance?

I will try to stand something up locally here and see if I run into any issues here.

Please let me know if you can provide the details from the question I have above or if have any further information to provide.

Thank you.

**Comment by binraider** [comment]
Hi @adam-werner, the issue was only being experienced in one of the setups, despite them being identical in configuration. We did fix it in the end by copying the folder in S3 (with 9gb of files) and then renaming the folders. Then it was okay! 

Sorry for the delay in reply, only it has been very hectic.

**Comment by adam-werner** [comment]
@binraider -- No worries!  I'm glad to hear that it's up-and-running well!  Thank you!
